### ISSUE TITLE
input and output

### ISSUE THREAD

**Issue by frollino** [infostreams/neural-network#3]
I can't understand if the input values must be between 0 and 1 or between -1 and +1 or... ? can you help me?

**Comment by infostreams** [comment]
Hi Frollino! The input can be any integer value, from PHP_INT_MIN (probably -2 billion) to PHP_INT_MAX (probably +2 billion). The same goes for the output node(s). 

It might be good to google around a bit and figure out how artificial neural networks work. The one that's implemented here is a very common and very simple multi-layer network. I did a quick google and found this page for you, which seems (as first glance) to be a decent introduction article: http://natureofcode.com/book/chapter-10-neural-networks/ You might need to skip over some of the parts though.

As this is not an issue with the code itself I will close it after this comment.
