### ISSUE TITLE
XOR Problem

### ISSUE THREAD

**Issue by umarsa** [infostreams/neural-network#6]
I am not sure if this is an issue or not but..

The following code:
$n->addTestData(array (-1, -1, 1), array (-1));
$n->addTestData(array (-1,  1, 1), array ( 1));
$n->addTestData(array ( 1, -1, 1), array ( 1));
$n->addTestData(array ( 1,  1, 1), array (-1));

Should this not be:
$n->addTestData(array (-1, -1, 0), array (-1));
$n->addTestData(array (-1,  1, 1), array ( 1));
$n->addTestData(array ( 1, -1, 1), array ( 1));
$n->addTestData(array ( 1,  1, 0), array (-1));

If not, what is the purpose of the third variable here if not the classification? If this third variable is not the classification (expected result) then how do you train this NN?

Thanks.

**Comment by umarsa** [comment]
This issue has been solved. The third parameter is a bias I believe.

The second parameter for the function addTestData is where the correct classification/result sits.

**Comment by infostreams** [comment]
Yes, the second parameter for the function is the expected result. I'm not sure anymore why the first parameter has three values in the array, to be honest. Pretty sure I copied it literally from the book I mention in the opening comments - and that was about a decade ago, so my memory is foggy :-)
